=== Pennsieve/model-schema-service/src/test/resources/schema/validator.json
{
  "$id": "http://schema.pennsieve.net/model/draft-01/schema",
  "$schema": "http://json-schema.org/draft-07/schema",
  "$comment": "This schema can be used to validate model templates for the Pennsieve platform.",
  "title": "Pennsieve Model Template Schema",
  "definitions": {
    "schemaArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#"
      }
    },
    "stringArray": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "default": []
    },
    "branchArray": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/branch"
      },
      "uniqueItems": true,
      "default": []
    },
    "branch": {
      "type": "object",
      "properties": {
        "source": {
          "const": "BIOPORTAL"
        },
        "acronym": {
          "type": "string"
        },
        "uri": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "maxDepth": {
          "$ref": "#/definitions/nonNegativeInteger"
        }
      },
      "additionalProperties": false
    },
    "simpleTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "object",
        "string"
      ]
    },
    "arrayValueTypes": {
      "enum": [
        "integer",
        "number",
        "string"
      ]
    },
    "itemSelector": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "number"
        },
        {
          "type": "integer"
        }
      ]
    },
    "enums": {
      "type": "array",
      "$comment": "Define a fixed array of valid values for the property",
      "items": {
        "$ref": "#/definitions/itemSelector"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "arrayItems": {
      "oneOf": [
        {
          "properties": {
            "type": {
              "$ref": "#/definitions/arrayValueTypes"
            },
            "enum": {
              "$ref": "#/definitions/enums"
            }
          },
          "required": [
            "type",
            "enum"
          ],
          "additionalProperties": false
        },
        {
          "properties": {
            "type": {
              "const": "string"
            },
            "branches": {
              "$comment": "Link value options to one or more branches of a published ontology",
              "$ref": "#/definitions/branchArray"
            }
          },
          "required": [
            "type",
            "branches"
          ],
          "additionalProperties": false
        }
      ]
    },
    "nonNegativeInteger": {
      "type": "integer",
      "minimum": 0
    },
    "schemaProps": {
      "$comment": "SchemaProps define how to provide the requirements for properties defined in the template",
      "properties": {
        "type": {
          "$ref": "#/definitions/simpleTypes"
        },
        "unit": {
          "type": "string",
          "$comment": "Provide a unit for the property value",
          "maxLength": 10
        },
        "enum": {
          "$ref": "#/definitions/enums"
        },
        "branches": {
          "$ref": "#/definitions/branchArray"
        },
        "description": {
          "type": "string",
          "$comment": "Provide a description for a property of the model template",
          "maxLength": 200
        },
        "items": {
          "$ref": "#/definitions/arrayItems"
        },
        "format": {
          "type": "string",
          "$comment": "If type is string, you can provide the format to specify date, email, or uri",
          "enum": [
            "date-time",
            "date",
            "time",
            "email",
            "uri"
          ]
        },
        "default": true,
        "additionalProperties": false
      },
      "required": [
        "type",
        "description"
      ],
      "additionalProperties": false
    }
  },
  "properties": {
    "$id": {
      "type": "string",
      "$comment": "This can be left blank and will be assigned by the Pennsieve platform"
    },
    "$schema": {
      "const": "http://schema.pennsieve.net/model/draft-01/schema",
      "$comment": "This identifies this document as an record of the Pennsieve model template"
    },
    "name": {
      "type": "string",
      "$comment": "This should be the name of the model that you provide a template for"
    },
    "description": {
      "type": "string",
      "$comment": "This is a description of the model",
      "maxLength": 200
    },
    "category": {
      "type": "string",
      "$comment": "Identifies the category of the model, which is used to group models on the platform",
      "maxLength": 50
    },
    "properties": {
      "type": "object",
      "$comment": "Here, the properties of the model template are defined",
      "additionalProperties": {
        "$ref": "#/definitions/schemaProps"
      },
      "default": {}
    },
    "required": {
      "$ref": "#/definitions/stringArray"
    }
  },
  "additionalProperties": false,
  "required": [
    "name",
    "$schema",
    "properties",
    "required",
    "description"
  ]
}

=== Pennsieve/model-schema-service/src/test/resources/json-definition-files/sample_protocol.json
{
  "$id": "",
  "$schema": "http://schema.pennsieve.net/model/draft-01/schema",
  "name": "Sample Protocol",
  "description": "Sample protocol based on the Nature Protocols schema.",
  "properties": {
    "abstract": {
      "type": "string",
      "description": "Please provide a brief description of the protocol."
    },
    "introduction": {
      "type": "string",
      "description": "Discuss the methods used in the protocol and the limitations."
    },
    "materials": {
      "type": "string",
      "description": "Please list every reagent and piece of equipment."
    },
    "procedure": {
      "type": "string",
      "description": "Provided as a numbered list of direct experimental instructions."
    },
    "timing": {
      "type": "string",
      "description": "please include a timeline indicating the approximate time each step or stage will take."
    },
    "troubleshooting": {
      "type": "string",
      "description": "Please include information on how to troubleshoot the most likely problems users will encounter with the protocol."
    },
    "anticipated results": {
      "type": "string",
      "description": "Please include information about the likely outcome of protocol"
    },
    "cfi": {
      "type": "string",
      "description": "Provide Conflict of Interest"
    },
    "acknowledgements": {
      "type": "string",
      "description": "Please note an acknowledgments section can be included."
    },
    "contribution statement": {
      "type": "string",
      "description": "Include a statement of responsibility in the manuscript that specifies the contribution of every author."
    },
    "supplementary information": {
      "type": "string",
      "description": "Provide other information related to the protocol."
    }
  },
  "required": [
    "abstract",
    "introduction",
    "procedure"
  ]
}

=== Pennsieve/model-schema-service/src/test/resources/json-definition-files/subject.json
{
  "$id": "",
  "$schema": "http://schema.pennsieve.net/model/draft-01/schema",
  "name": "Sample Subject",
  "description": "Sample subject model.",
  "properties": {
    "name": {
      "type": "string",
      "description": "Please provide a name for the subject."
    },
    "age": {
      "type": "number",
      "description": "Please provide an age for the subject."
    },
    "description": {
      "type": "string",
      "description": "Please provide any additional information about the subject."
    },
    "sex": {
      "type": "string",
      "description": "Please provide the sex of the subject.",
      "enum": [
        "male",
        "female",
        "unknown",
        "other"
      ]
    },
    "species": {
      "type": "string",
      "description": "please specifiy the species of the subject.",
      "enum": [
        "human",
        "cat",
        "dog",
        "fish",
        "bird",
        "mouse",
        "rat",
        "sheep",
        "rabbits",
        "chimpanzee",
        "monkey",
        "pig",
        "other"
      ]
    },
    "weight": {
      "type": "number",
      "description": "Please provide the weight of the subject."
    }
  },
  "required": [
    "name",
    "sex",
    "species"
  ]
}

=== Pennsieve/model-schema-service/src/test/resources/json-definition-files/intervention.json
{
  "$schema": "http://schema.pennsieve.net/model/draft-01/schema",
  "name": "Intervention",
  "description": "This model defines an intervention",
  "category": "Protocol",
  "properties": {
    "Event or stressor description": {
      "type": "string",
      "description": "Description of Event or stressor"
    },
    "Start time": {
      "type": "string",
      "description": "Start time of the intervention"
    },
    "Stop time": {
      "type": "string",
      "description": "Stop time of the intervention"
    },
    "Minimum washout or recovery time": {
      "type": "string",
      "description": "Description of Minimum washout or recovery time"
    }
  },
  "required": [
    "Event or stressor description",
    "Start time",
    "Stop time"
  ]
}

=== Pennsieve/model-schema-service/src/test/resources/json-definition-files/acquisition.json
{
  "$schema": "http://schema.pennsieve.net/model/draft-01/schema",
  "name": "Acquisition",
  "description": "A representation of an acquisition of data by a recording device",
  "category": "Acquisition",
  "properties": {
    "Acquisition Type": {
      "type": "string",
      "description": "The type of acquisition"
    },
    "Recording Type": {
      "type": "string",
      "description": "The type of recording"
    },
    "Description and characteristics of sensor": {
      "type": "string",
      "description": "Describe the sensor and provide information on its characteristics"
    },
    "Spatial information sensor": {
      "type": "string",
      "description": "Describe the spatial location of sensor and how it is affixed to biological target"
    },
    "A/D conversion (sampling rate, dynamic range, any signal processing)": {
      "type": "string",
      "description": "Describe A/D conversion (sampling rate, dynamic range, any signal processing)"
    },
    "Calibration - start/stop time": {
      "type": "string",
      "description": "Indicate the start and stop time of the calibration process"
    },
    "Setting for detection - pinhole/gain, offset, scan mode, temporal sampling": {
      "type": "string",
      "description": "Describe the settings for detection in an optical recording."
    },
    "Size of scanned field and resolution of sampling": {
      "type": "string",
      "description": "Describe the size of the scanned field and resolution of sampling in an optical recording."
    },
    "Characteristics of pre-amplifier and amplifiers (gain, filter setting)": {
      "type": "string",
      "description": "Describe the characteristics of the pre-amplifier and amplifiers (gain, filter settings)"
    },
    "Timing control": {
      "type": "string",
      "description": "Describe the timing control for multiple recording systems/stimulation/recording/imaging etc."
    },
    "Hardware based data processing (ﬁltering/smoothing/binning/ etc.)": {
      "type": "string",
      "description": "Describe hardware based data processing (ﬁltering/smoothing/binning/ etc.)"
    },
    "Software environment (operating system/acquisition program version and supplier/etc.)": {
      "type": "string",
      "description": "Describe software environment (operating system/acquisition program version and supplier/etc.)"
    }
  },
  "required": []
}

=== Pennsieve/model-schema-service/src/test/resources/json-definition-files/specimen.json
{
  "$schema": "http://schema.pennsieve.net/model/draft-01/schema",
  "name": "Specimen",
  "description": "A representation of a specimen (human, animal, or tissue sample)",
  "category": "Specimen",
  "properties": {
    "Gender": {
      "type": "string",
      "description": "Gender of the specimen",
      "enum": [
        "M",
        "F"
      ]
    },
    "Age": {
      "type": "string",
      "description": "The age of the specimen"
    },
    "Developmental stage": {
      "type": "string",
      "description": "Developmental stage of the specimen"
    },
    "Body Mass Index": {
      "type": "string",
      "description": "Body mass index"
    },
    "Clinical/disease information": {
      "type": "string",
      "description": "Describe clinical and disease information"
    },
    "Drug Information": {
      "type": "string",
      "description": "Describe drug information"
    },
    "Family history": {
      "type": "string",
      "description": "Describe family history"
    },
    "Time point on circadian clock": {
      "type": "string",
      "description": "Time point on circadian clock"
    },
    "Time point on oestrous cycle": {
      "type": "string",
      "description": "Time point on oestrous cycle"
    },
    "Concious, sedated or anesthetized": {
      "type": "string",
      "description": "Concious, sedated or anesthetized",
      "enum": [
        "N/A",
        "Concious",
        "sedated",
        "anesthetized"
      ]
    },
    "Sedation Dose": {
      "type": "string",
      "description": "Sedation Dose"
    },
    "Sedation Source": {
      "type": "string",
      "description": "Sedation Source"
    },
    "Sedation Vehicle": {
      "type": "string",
      "description": "Sedation Vehicle"
    },
    "Sedation Administration Route": {
      "type": "string",
      "description": "Sedation Administration Route",
      "enum": [
        "N/A",
        "ip",
        "iv",
        "im",
        "sc",
        "inh",
        "oral",
        "topical",
        "other"
      ]
    },
    "Sedation Frequency": {
      "type": "string",
      "description": "Sedation Frequency"
    },
    "Sedation Start Time": {
      "type": "string",
      "description": "Sedation Start Time"
    },
    "Sedation Stop Time": {
      "type": "string",
      "description": "Sedation Stop Time"
    },
    "Anesthesia Dose": {
      "type": "string",
      "description": "Anesthesia Dose"
    },
    "Anesthesia Source": {
      "type": "string",
      "description": "Anesthesia Source"
    },
    "Anesthesia Vehicle": {
      "type": "string",
      "description": "Anesthesia Vehicle"
    },
    "Anesthesia Administration Route": {
      "type": "string",
      "description": "Anesthesia Administration Route",
      "enum": [
        "N/A",
        "ip",
        "iv",
        "im",
        "sc",
        "inh",
        "oral",
        "topical",
        "other"
      ]
    },
    "Anesthesia Frequency": {
      "type": "string",
      "description": "Anesthesia Frequency"
    },
    "Anesthesia Start Time": {
      "type": "string",
      "description": "Anesthesia Start Time"
    },
    "Anesthesia Stop Time": {
      "type": "string",
      "description": "Anesthesia Stop Time"
    },
    "Open Cavity Procedure": {
      "type": "string",
      "description": "Was this an open cavity procedure?",
      "enum": [
        "Y",
        "N"
      ]
    },
    "Chronic Intervention": {
      "type": "string",
      "description": "Was this a chronic Intervention",
      "enum": [
        "Y",
        "N"
      ]
    },
    "Intervention History": {
      "type": "string",
      "description": "What was the intervention history?"
    },
    "Weight": {
      "type": "string",
      "description": "Weight"
    },
    "genus/species/strain": {
      "type": "string",
      "description": "Genus/species/strain"
    },
    "Supplier": {
      "type": "string",
      "description": "Supplier"
    },
    "Genetic variation (type/means)": {
      "type": "string",
      "description": "Genetic variation (type/means)"
    },
    "Disease model/state": {
      "type": "string",
      "description": "Disease model/state"
    },
    "Husbandry": {
      "type": "string",
      "description": "Husbandry (diet/housing type/environmental enrichment; day/night cycle)"
    },
    "Method of euthanasia": {
      "type": "string",
      "description": "Method of euthanasia"
    },
    "Cellular and acellular composition": {
      "type": "string",
      "description": "Cellular and acellular composition"
    },
    "Growth Time": {
      "type": "string",
      "description": "Growth Time"
    },
    "Growth Temperature": {
      "type": "string",
      "description": "Growth temperature"
    },
    "Growth media": {
      "type": "string",
      "description": "Growth media"
    },
    "Growth substrate": {
      "type": "string",
      "description": "Growth substrate"
    },
    "Bioreactor": {
      "type": "string",
      "description": "Bioreactor"
    },
    "Growth supplements": {
      "type": "string",
      "description": "Growth supplements"
    },
    "Growth Stimulation (electrical/mechanical)": {
      "type": "string",
      "description": "Growth Stimulation (electrical/mechanical)"
    },
    "Cell selection process for recording": {
      "type": "string",
      "description": "Cell selection process for recording"
    },
    "Cell line": {
      "type": "string",
      "description": "Cell line"
    },
    "Origin of Sample": {
      "type": "string",
      "description": "Origin of Sample"
    },
    "Passage (number/conditions/density)": {
      "type": "string",
      "description": "Passage (number/conditions/density)"
    },
    "Anatomical origin of sample": {
      "type": "string",
      "description": "Anatomical origin of sample, mapped to species/organ specific scaffolding"
    },
    "Perfusion protocol for organ; isolated tissue or isolated cell": {
      "type": "string",
      "description": "Perfusion protocol for organ; isolated tissue or isolated cell"
    },
    "Isolation procedure for organ; isolated tissue or isolated cell": {
      "type": "string",
      "description": "Isolation procedure for organ; isolated tissue or isolated cell"
    },
    "Indices used for assessment of viability for organ, isolated tissue or isolated cell": {
      "type": "string",
      "description": "Indices used for assessment of viability for organ, isolated tissue or isolated cell"
    }
  },
  "required": []
}

=== Pennsieve/model-schema-service/src/test/resources/json-definition-files/sedation.json
{
  "$schema": "http://schema.pennsieve.net/model/draft-01/schema",
  "name": "Sedation Information",
  "description": "This model provides information about the sedation procedure",
  "category": "None",
  "properties": {
    "Sedation Source": {
      "type": "string",
      "description": "The Sedation Source"
    },
    "Sedation Vehicle": {
      "type": "string",
      "description": "The Sedation Vehicle"
    },
    "Sedation Administration Route": {
      "type": "string",
      "description": "The administration route of the sedation",
      "enum": [
        "ip",
        "iv",
        "im",
        "sc",
        "inh",
        "oral",
        "topical",
        "other"
      ]
    },
    "Sedation Frequency": {
      "type": "string",
      "description": "The frequency of the sedation"
    },
    "Sedation Start Time": {
      "description": "The start time of the sedation",
      "type": "string"
    },
    "Sedation Stop Time": {
      "description": "The stop time of the sedation",
      "type": "string"
    }
  },
  "required": [
    "Sedation Source",
    "Sedation Vehicle"
  ]
}

=== Pennsieve/model-schema-service/src/test/resources/json-definition-files/study_design.json
{
  "$schema": "http://schema.pennsieve.net/model/draft-01/schema",
  "name": "Study Design",
  "description": "This model defines a Study Design",
  "category": "Protocol",
  "properties": {
    "Randomization and blinding procedures": {
      "type": "string",
      "description": "Description of Randomization and blinding procedures"
    },
    "Inclusion/exclusion criteria": {
      "type": "string",
      "description": "Description of Inclusion/exclusion criteria"
    },
    "Groups and group size": {
      "type": "string",
      "description": "Description of group and group size"
    },
    "Rationale for exclusion decision": {
      "type": "string",
      "description": "Describe rationale for excluding subject from final analysis"
    }
  },
  "required": [
    "Randomization and blinding procedures",
    "Inclusion/exclusion criteria",
    "Groups and group size"
  ]
}
